### PR TITLE
Add options to disable default props in snapshot

### PR DESCRIPTION
**Pull request by VincentLanglet**
@adriantoine Hi !

I cherry-pick the @madou commit.
I cherry-pick the @jiangzhu-genie commit in [this PR](https://github.com/adriantoine/enzyme-to-json/pull/112)
And then I add an option `ignoreDefaultProps` to add this behaviour.

This way there is no breaking changes. Fixing https://github.com/adriantoine/enzyme-to-json/issues/99

### CODE REVIEW

**Comment by landonalder** [comment]
Would be great to have this 👍

**Comment by bradbarrow** [comment]
We'd love to have this feature @ Redbubble. 

Our Design System package ships into many discrete apps in our company and every time we add new default props to components (which should be non-breaking) our internal customer's builds break because their snapshots change.

Having this option would relieve them of a lot of unnecessary work and enable our Design System updates to be far more seamless.

Thank you for working on this - would be great to see it released @adriantoine

**Comment by maurobender** [comment]
I love to see this merged since in a project I'm working on we use a library with components with a lot of big default props that make the snapshots so big they are almost useless.

**Comment by VincentLanglet** [comment]
I will maybe post a tweet https://twitter.com/adriantoine

If he doesn't maintain the library he should share the property

**Comment by adriantoine** [comment]
Nice one, thanks for your contribution!!

**Pull request merged**
