### PR TITLE
Add serializerDeep

### PR DESCRIPTION
**Pull request by vlad-zhukov**
Added a serializer with a deep mode. Also fixed exports.

### CODE REVIEW

**Comment by adriantoine** [comment]
Hi @vlad-zhukov, thanks for your contribution!

For the `serializerDeep`, it's a good idea but then I'd want to support the `shallow` option and also the `noKey` one, in that case make I'd like to support an import path like that: `enzyme-to-json/serializer/deep`, `enzyme-to-json/serializer/shallow`, `enzyme-to-json/serializer/noKey`, etc... Can you make that change?

And about the export, I won't accept this as these are not equivalent:

```js
export function a() {};
export function b() {};
```

and

```js
module.exports = {
  a: function a() {},
  b: function b() {}
};
```

because, for example if you import it like that

```js
import myModule from 'myModule';
```

you'll get `undefined` in the first case as there is no default export, and you would get an object in the second case. You can test it here: https://www.webpackbin.com/bins/-Ku_n_TzjarSS8be9O0c

Since I don't know they import it in Jest, I prefer doing it as they say [in the docs](https://facebook.github.io/jest/docs/en/configuration.html#snapshotserializers-array-string).

**Comment by vlad-zhukov** [comment]
You are mixing CommonJS and ES modules. Jest runs in Node and uses CommonJS, and from CJS point
```js
exports.a = function a() {};
exports.b = function b() {};
```
and
```js
module.exports = {
  a: function a() {},
  b: function b() {}
};
``` 
are kinda equivalent because they both can be consumed in the same way like 
```js
const {a, b} = require('./myModule');
```

[As you can see here](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=KYDwDg9gTgLgBAMwK4DsDGMCWEVwIYAUAlHAN4C-QA&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=es2015&prettier=false&targets=&version=6.26.0), babel transpiles ES `export function a() {}` into `exports.a = function a() {}`.

I've updated your example, have a look: https://www.webpackbin.com/bins/-KucivVWqc_rECqIKzxB

**Comment by adriantoine** [comment]
Hi!

I'm not mixing CommonJS and ES modules, when you use the export
```js
export function a() {};
export function b() {};
```

you are using ES modules which are going

**Comment by adriantoine** [comment]
Hi!

I'm not mixing CommonJS and ES modules, when you use the export statement

```js
export function a() {};
export function b() {};
```

you are using ES modules, and what I said above is true for ES modules. Babel transpile them to CommonJS modules because that's the only way to make them work in a Node environment, not because that's the way they work internally.

ES modules are coming to Node (and yes, I know it's in a "complicated" state at the moment) so maybe at some point we won't transpile `import` and `export` statements anymore. [In this example](https://facebook.github.io/jest/docs/en/expect.html#expectaddsnapshotserializerserializer) from Jest docs, they import it like in my first WebpackBin so that would fail if we stop transpiling export statements.

In any case the [Jest documentation](https://facebook.github.io/jest/docs/en/configuration.html#snapshotserializers-array-string) shows that we should use `module.exports` so that's what we're going to use until they update the docs (if they do) and I don't see the benefits of switching to `export` statements anyway.

**Comment by vlad-zhukov** [comment]
I see.

By the way I've found [`setupTestFrameworkScriptFile`](https://facebook.github.io/jest/docs/en/configuration.html#setuptestframeworkscriptfile-string) setting (there is a CLI arg as well), and it looks like a great alternative to `snapshotSerializers`. Using it like this right now:
```js
import toJson from 'enzyme-to-json';
import {isEnzymeWrapper} from 'enzyme-to-json/utils';

const enzymeSerializer = {
    test(wrapper) {
        return isEnzymeWrapper(wrapper);
    },
    print(wrapper, serializer) {
        return serializer(toJson(wrapper, {mode: 'deep'}));
    }
};

expect.addSnapshotSerializer(enzymeSerializer);
```

WDYT? Wouldn't it be better to have a single function instead of supporting separate files?

**Comment by adriantoine** [comment]
Yeah it looks pretty interesting, sorry I don't have time to have a look for now but well yeah I'd much prefer to have a single function, that would be great.

I can have a look tomorrow, feel free to make a PR or update this one, sorry for the lack of support.

**Comment by adriantoine** [comment]
Closing this one as #76 is a better solution.

**Pull request closed without merging**
