### PR TITLE
feat(react-fragments): support react fragments

### PR DESCRIPTION
**Pull request by madou**
Closes #90 

Hi there, tried my hand at supporting fragments.

Atm I'm just hacking around `typeName` from `enzyme/build/Debug` not supporting fragments. Might be better placed modifying their library to support it - maybe (or maybe not, perhaps it's not something they should do)?

Oh, I've also I added a `.prettierrc` that matches the code base  - let me know what you think.

Cheers!

### CODE REVIEW

**Comment by madou** [comment]
Getting a snapshot failure for keys: https://travis-ci.org/adriantoine/enzyme-to-json/jobs/316131352#L512

Might be because I've upgraded react? Good to regen @adriantoine ?

**Comment by tdeekens** [comment]
Thanks a lot for taking this on!

**Comment by adriantoine** [comment]
Hi @madou,
Thanks a lot for your PR! Let me have a look, I'll review it asap.

**Comment by adriantoine** [comment]
Hey @madou, I wouldn't worry about this key issue, from what I can see, it's actually a bug but nothing to do with your code, I'll fix that later. I'm happy to merge your PR for now.

And thanks a lot for your `.prettierrc`! I didn't have time to update the settings. 😄

**Comment by madou** [comment]
No worries, thanks for the merge!

**Pull request merged**
