### PR TITLE
Skip undefined props in snapshot (fixes #21)

### LINKED ISSUE #21: Undefined properties are rendered into snapshot
Not sure if this is a bug or a feature but after updating to the latest version all my snapshots contains `someProp={undefined}` for all props that are not defined in the test.

### PR DESCRIPTION
**Pull request by existentialism**

### CODE REVIEW

**Comment by adriantoine** [comment]
Looks great, just waiting for travis status to go green, thanks @existentialism!

**Comment by adriantoine** [comment]
@existentialism Travis tests are failing, you still need `lodash.omit` in the `package.json` for `mount.js`, can you update the PR?

**Comment by existentialism** [comment]
Oh derp, missed that sorry.

Do we want the snapshot behaviors around undefined props to differ between mount and shallow?

**Comment by adriantoine** [comment]
That's a good point, would be great if you do the same thing there: https://github.com/adriantoine/enzyme-to-json/blob/3d04485e0559396183f447c0cd18cd077cade175/src/mount.js#L24 thanks!

**Comment by adriantoine** [comment]
And then we won't need `lodash.omit`

**Comment by existentialism** [comment]
@adriantoine updated, sorry again for missing that.

**Comment by adriantoine** [comment]
@existentialism no problem at all 😊 Thanks a lot for your contribution!!

**Pull request merged**
