### PR TITLE
docs: Add example to simulate click and then match snapshot

### PR DESCRIPTION
**Pull request by pedrottimark**
Thinking more how I follow clear and short examples:

What do you think about an example of changing the state by simulating an event to contrast with calling `setState` directly in the existing example?

Some blog articles that I have read debate how much to call lifecycle methods in tests.

### CODE REVIEW

**Comment by pedrottimark** [comment]
If you approve this change, I will need to edit `test\examples.test.js` and update its snapshot.

**Comment by adriantoine** [comment]
Hi again @pedrottimark!

Sorry but I want to keep the readme simple. The goal of this part is to show that you can use handy Enzyme wrapper functions and get a snapshot, but we don't have to demonstrate every Enzyme function, even if `simulate` is in Enzyme's readme.

If I had to change the readme, I'd rather show more example for `mount` and `render` wrappers, but it's not a big priority.

Thanks!

**Comment by pedrottimark** [comment]
Yes, I agree that less is more, for the win :)

Here is a last question, from how your excellent project was recommended in an issue on Jest:

* https://github.com/facebook/jest/issues/2197#issuecomment-264664134
* https://github.com/facebook/jest/issues/2197#issuecomment-264987874

What do you think about the idea for it to become a `.toJSON` method in Enzyme package itself, so API to take a shallow snapshot becomes parallel to deep snapshot with `react-test-renderer`?

**Comment by adriantoine** [comment]
I don't think it will ever become an internal Enzyme method, see https://github.com/airbnb/enzyme/pull/541, Enzyme maintainers are opposed (and I respect that).

You may be interested in this: https://twitter.com/cpojer/status/806138327233609728

**Comment by adriantoine** [comment]
And I'm glad my project has been recommended, I didn't know actually 😮😊

**Comment by pedrottimark** [comment]
Thank you for your patience to explain.

**Pull request closed without merging**
