### PR TITLE
Fix mountToJson not rendering mixed children

### LINKED ISSUE #35: mountToJson doesn't render mixed children
This is the same bug that is fixed in https://github.com/airbnb/enzyme/pull/476

### PR DESCRIPTION
**Pull request by prayogoa**
fixes #35

### CODE REVIEW

**Comment by adriantoine** [comment]
Hi @prayogoa, thanks for your contribution! It looks amazing but as you can see the code coverage is going down, can you provide a unit test?

**Comment by prayogoa** [comment]
@adriantoine specs added!

**Comment by adriantoine** [comment]
@prayogoa thanks!

**Comment by adriantoine** [comment]
Your fix has been released in `v1.4.5` 👌🎉

**Pull request merged**
