### PR TITLE
Reintroduced Node 4 support

### LINKED ISSUE #70: Node 4 support
Node 4 was removed in 1.6.0 without any mention of that in the change log. It’s a breaking change so it should have been a major release.

Any reason to do that while Enzyme still supports Node 4?

### PR DESCRIPTION
**Pull request by adriantoine**
Fixes #70

### CODE REVIEW

**Comment by sapegin** [comment]
Let’s wait for the CI 🙏

**Comment by adriantoine** [comment]
Seems fixed now, I'll merge and publish a new version.

**Comment by adriantoine** [comment]
I just published it as a patch released (`v2.0.1`) as it shouldn't be a breaking change.

**Comment by sapegin** [comment]
Awesome, thanks! It works now 🍕

**Comment by adriantoine** [comment]
No problem, sorry for the inconvenience!

**Pull request merged**
